In [365]:
import numpy as np

In [366]:
# returns the transpose of A times A
def ATxA(A):
    return np.matrix(A).transpose() * A

In [367]:
# returns the transpose of A times A
def AxAT(A):
    return A * np.matrix(A).transpose()

In [368]:
def SingularValues(ATA):
    eigenvalues, eigenvectors = np.linalg.eigh(ATA)
    
    # Order eigenvalues in descending order
    idx = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[idx]
    
    return np.sqrt(eigenvalues)
    

In [369]:
def V(ATA):
    eigenvalues, eigenvectors = np.linalg.eigh(ATA)
    
    # Order eigenvalues and corresponding vectors in descending order
    idx = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[idx]
    eigenvectors = eigenvectors[:, idx]

    # normalize
    for i in range(eigenvectors.shape[1]):
        norm = np.linalg.norm(eigenvectors[:, i])
        if norm > 0:
            eigenvectors[:, i] /= norm

    return np.matrix(eigenvectors)
        
    

In [370]:
def SVD(A):
    ATA = ATxA(A)
    AAT = AxAT(A)
    
    # Singular Value Matrix
    S_vec = SingularValues(ATA)
    S_mat = np.zeros(A.shape)
    for i in range(S_vec.size):
        S_mat[i,i] = S_vec[i]
    
    # V transpose matrix
    V_mat = V(ATA).transpose()
    
    # U matrix
    U_mat = V(AAT)
    return U_mat, S_mat, V_mat

In [371]:
b = np.matrix([[1,0,1],[0,1,0],[0,1,1],[0,1,0],[1,1,0]])
U_mat, S_mat, V_mat = SVD(b)
print(U_mat)
print(S_mat)
print(V_mat)
print(np.round(U_mat*S_mat*V_mat, 2))

[[-3.65148372e-01  8.16496581e-01  7.84245057e-17 -7.70698864e-02
   4.40522681e-01]
 [-3.65148372e-01 -4.08248290e-01  4.44089210e-16  6.19457630e-01
   5.62380871e-01]
 [-5.47722558e-01 -7.02491948e-17  7.07106781e-01  7.70698864e-02
  -4.40522681e-01]
 [-3.65148372e-01 -4.08248290e-01 -1.65188709e-16 -7.73597403e-01
   3.18664491e-01]
 [-5.47722558e-01 -1.47380436e-17 -7.07106781e-01  7.70698864e-02
  -4.40522681e-01]]
[[2.23606798 0.         0.        ]
 [0.         1.41421356 0.        ]
 [0.         0.         1.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [ 5.77350269e-01 -5.77350269e-01  5.77350269e-01]
 [-7.07106781e-01  2.59129669e-16  7.07106781e-01]]
[[ 1. -0.  1.]
 [-0.  1.  0.]
 [ 0.  1.  1.]
 [ 0.  1. -0.]
 [ 1.  1.  0.]]
